### PR TITLE
Added API's test cases for Job's and feedbacks & connectors

### PR DESCRIPTION
**Pull request by Himanshu1231231**
5 API Test cases for Job's and feedbacks & connectors - 
1. - getConnectorsCategories
2. - getConnectors
3. - getJobtitles
4. - getFeedbacksCategories
5. - getJobtitles

### CODE REVIEW

**Review by ishubham1995 — APPROVED** [review]
LGTM

**Review by yadavravinder — APPROVED** [review]
LGTM

**Comment by yadavravinder** [comment]
Please resolve conflicts!

**Comment by Himanshu1231231** [comment]
> Please resolve conflicts!

Done

**Pull request merged**
