### PR TITLE
Added API's test cases for dashboard feedback and models

### PR DESCRIPTION
**Pull request by Himanshu1231231**
Automated 5 test cases of API's and fixed some test cases.
1- /api/v2/dashboard-feedback/
2- /api/v2/member/feedbacks/ (GET)
3- /api/v2/member/feedbacks/ (GET By ID)
4- /api/v2/models/ (GET)
5- /api/v2/models/ (GET By ID)

pass
pass 1

### CODE REVIEW

**Comment by yadavravinder** [comment]
Please add Artifacts for pass or fail !!

**Review by ishubham1995 — APPROVED** [review]
LGTM

**Comment by Himanshu1231231** [comment]
> Please add Artifacts for pass or fail !!

Done

**Review by yadavravinder — APPROVED** [review]
LGTM

**Pull request merged**
