### PR TITLE
Added API test cases for CB user.

### PR DESCRIPTION
**Pull request by ishubham1995**
5 api added for CB users
1. Get - /api/v2/cb-users/
2. Post- /api/v2/cb-users/
3. Get - /api/v2/cb-users/{id}/
4. Put- /api/v2/cb-users/{id}/
5. Patch-/api/v2/cb-users/{id}/

### CODE REVIEW

**Review by TiwariMithilesh — COMMENTED** [review]
Please Change the Summary.

**Review by TiwariMithilesh — APPROVED** [review]
LGTM

**Review by anishcb — CHANGES_REQUESTED** [review]
Why you are passing app_id as a argument because there is no need of any app_id please correct this.

**Review by TiwariMithilesh — APPROVED** [review]
LGTM

**Review by anishcb — APPROVED** [review]
LGMT

**Pull request merged**
