### PR TITLE
Added API's test cases for totp and users api

### PR DESCRIPTION
**Pull request by Himanshu1231231**
Automated 5 New API's test cases - 
1- /api/v2/totp/device/remove/
2- /api/v2/user/
3- /api/v2/user/(put)
4- /api/v2/users/(get)
5- /api/v2/users/(get by id)

### CODE REVIEW

**Review by ishubham1995 — APPROVED** [review]
LGTM

**Comment by anishcb** [comment]
Hi team,

I would like to mention that we should not mark a pull request as "LGTM" without a thorough review. If you don't have time to review it properly, please refrain from reviewing it. However, please do not approve it without checking. Thank you.

**Review by ishubham1995 — APPROVED** [review]
LGTM

**Review by TiwariMithilesh — APPROVED** [review]
Looks Good!!!!

**Pull request merged**
