### PR TITLE
Get: API for FE settings list: Catalog - api/v2/settings/fe/

### PR DESCRIPTION
**Pull request by ishubham1995**
Automated API

### CODE REVIEW

**Review by TiwariMithilesh — COMMENTED** [review]
Please change summary.

**Review by TiwariMithilesh — APPROVED** [review]
LGTM!!!

**Review by Himanshu1231231 — APPROVED** [review]
LGTM

**Review by anishcb — COMMENTED** [review]
It looks good so we can merge.

**Pull request merged**
